# Generated by Django 3.2.8 on 2021-10-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_baseuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataunit',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='offers_title_image', verbose_name='Заглавное изображение'),
        ),
    ]
