# Generated by Django 3.2.8 on 2021-10-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dataunit_title_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataunit',
            name='document',
        ),
        migrations.AddField(
            model_name='dataunit',
            name='document1',
            field=models.FileField(blank=True, upload_to='addition_files', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='dataunit',
            name='document2',
            field=models.FileField(blank=True, upload_to='addition_files', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='dataunit',
            name='document3',
            field=models.FileField(blank=True, upload_to='addition_files', verbose_name='Файл'),
        ),
    ]
